[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
dependsOn = ["setup"]
cmds = ["python -m venv /opt/venv", ". /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = ". /opt/venv/bin/activate && gunicorn app:app --bind 0.0.0.0:$PORT"